export const offlineSpanishDictionary = [
  { w: "Abeja", d: "Insecto que produce miel y cera." },
  { w: "Abrazo", d: "Muestra de afecto rodeando con los brazos." },
  { w: "Agua", d: "Líquido transparente, incoloro, inodoro e insípido." },
  { w: "Aire", d: "Mezcla gaseosa que envuelve la Tierra." },
  { w: "Alegría", d: "Sentimiento de placer y felicidad." },
  { w: "Amigo", d: "Persona con la que se tiene amistad." },
  { w: "Amor", d: "Sentimiento de vivo afecto e inclinación." },
  { w: "Árbol", d: "Planta de tronco leñoso y elevado." },
  { w: "Arte", d: "Manifestación de la actividad humana creativa." },
  { w: "Aventura", d: "Suceso extraño y emocionante." },
  { w: "Azul", d: "Color del cielo sin nubes." },
  { w: "Baile", d: "Movimiento del cuerpo al ritmo de la música." },
  { w: "Barco", d: "Construcción cóncava de madera o hierro que flota." },
  { w: "Belleza", d: "Cualidad de una persona o cosa que agrada a la vista." },
  { w: "Beso", d: "Acto de presionar los labios contra algo." },
  { w: "Blanco", d: "Color de la nieve o de la leche." },
  { w: "Bosque", d: "Extensión de terreno densamente poblada de árboles." },
  { w: "Brillo", d: "Luz que emite o refleja un cuerpo." },
  { w: "Bueno", d: "Que tiene bondad en su género." },
  { w: "Caballo", d: "Mamífero solípedo de gran tamaño." },
  { w: "Cielo", d: "Atmósfera que rodea la Tierra." },
  { w: "Ciudad", d: "Población de importancia." },
  { w: "Comida", d: "Sustancia que se ingiere para subsistir." },
  { w: "Corazón", d: "Órgano central de la circulación de la sangre." },
  { w: "Cristal", d: "Sólido transparente y frágil." },
  { w: "Cuerpo", d: "Conjunto de las partes que forman un ser vivo." },
  { w: "Danza", d: "Baile, acción de bailar." },
  { w: "Deporte", d: "Actividad física reglamentada y competitiva." },
  { w: "Deseo", d: "Interés o apetencia por algo." },
  { w: "Día", d: "Tiempo que la Tierra tarda en dar una vuelta." },
  { w: "Dinero", d: "Medio de cambio corriente." },
  { w: "Dulce", d: "Que tiene sabor a azúcar." },
  { w: "Espejo", d: "Superficie que refleja la imagen." },
  { w: "Estrella", d: "Cuerpo celeste que brilla con luz propia." },
  { w: "Familia", d: "Grupo de personas emparentadas entre sí." },
  { w: "Flor", d: "Parte de la planta que contiene los órganos reproductores." },
  { w: "Fuego", d: "Calor y luz producidos por la combustión." },
  { w: "Gato", d: "Mamífero felino doméstico." },
  { w: "Grande", d: "Que supera en tamaño a lo común." },
  { w: "Guerra", d: "Lucha armada entre dos o más naciones." },
  { w: "Guitarra", d: "Instrumento musical de cuerda." },
  { w: "Hermoso", d: "Que tiene hermosura." },
  { w: "Historia", d: "Narración de hechos pasados." },
  { w: "Hombre", d: "Ser humano de sexo masculino." },
  { w: "Idea", d: "Representación mental de algo." },
  { w: "Isla", d: "Porción de tierra rodeada de agua." },
  { w: "Jardín", d: "Terreno donde se cultivan plantas y flores." },
  { w: "Juego", d: "Actividad recreativa física o mental." },
  { w: "Libertad", d: "Facultad de obrar por propia voluntad." },
  { w: "Libro", d: "Conjunto de hojas de papel encuadernadas." },
  { w: "Luna", d: "Satélite natural de la Tierra." },
  { w: "Luz", d: "Agente físico que hace visibles los objetos." },
  { w: "Madre", d: "Mujer que ha tenido un hijo." },
  { w: "Mano", d: "Parte del cuerpo humano que va desde la muñeca." },
  { w: "Mar", d: "Masa de agua salada que cubre la mayor parte de la Tierra." },
  { w: "Miedo", d: "Sensación de angustia por un peligro." },
  { w: "Montaña", d: "Elevación natural del terreno." },
  { w: "Mujer", d: "Ser humano de sexo femenino." },
  { w: "Mundo", d: "Conjunto de todo lo existente." },
  { w: "Música", d: "Arte de combinar los sonidos." },
  { w: "Noche", d: "Tiempo entre la puesta y la salida del sol." },
  { w: "Nombre", d: "Palabra que designa a los seres o cosas." },
  { w: "Nube", d: "Masa de vapor de agua suspendida en la atmósfera." },
  { w: "Ojo", d: "Órgano de la vista." },
  { w: "Oro", d: "Metal precioso de color amarillo." },
  { w: "Padre", d: "Varón que ha tenido un hijo." },
  { w: "Palabra", d: "Unidad lingüística con significado." },
  { w: "Paz", d: "Situación en la que no hay guerra." },
  { w: "Pelo", d: "Filamento que nace en la piel de los mamíferos." },
  { w: "Pensar", d: "Imaginar o considerar algo." },
  { w: "Pequeño", d: "Que tiene poco tamaño." },
  { w: "Perro", d: "Mamífero canino doméstico." },
  { w: "Piedra", d: "Materia mineral dura y sólida." },
  { w: "Pintura", d: "Obra pintada sobre una superficie." },
  { w: "Plata", d: "Metal de color blanco brillante." },
  { w: "Poder", d: "Facultad o potencia de hacer algo." },
  { w: "Puerta", d: "Abertura en una pared para entrar o salir." },
  { w: "Radio", d: "Aparato para recibir ondas electromagnéticas." },
  { w: "Río", d: "Corriente natural de agua continua." },
  { w: "Rojo", d: "Color de la sangre o del tomate." },
  { w: "Rosa", d: "Flor del rosal." },
  { w: "Saber", d: "Tener conocimiento de algo." },
  { w: "Sal", d: "Sustancia blanca que se usa para condimentar." },
  { w: "Sangre", d: "Líquido rojo que circula por las arterias y venas." },
  { w: "Sol", d: "Estrella luminosa centro de nuestro sistema planetario." },
  { w: "Sueño", d: "Estado de reposo al dormir." },
  { w: "Tierra", d: "Planeta que habitamos." },
  { w: "Tiempo", d: "Magnitud física que permite ordenar los sucesos." },
  { w: "Trabajo", d: "Actividad física o intelectual remunerada." },
  { w: "Universo", d: "Conjunto de todo lo que tiene existencia física." },
  { w: "Vacaciones", d: "Periodo de descanso sin trabajar o estudiar." },
  { w: "Vaso", d: "Recipiente para beber líquidos." },
  { w: "Viento", d: "Corriente de aire producida en la atmósfera." },
  { w: "Vida", d: "Existencia de los seres vivos." },
  { w: "Vino", d: "Bebida alcohólica obtenida de la uva." },
  { w: "Voz", d: "Sonido producido por las cuerdas vocales." },
  { w: "Zapato", d: "Calzado que cubre el pie hasta el tobillo." },
  { w: "Abadía", d: "Monasterio o iglesia regidos por un abad o una abadesa." },
  { w: "Abismo", d: "Profundidad grande, imponente y peligrosa." },
  { w: "Bóveda", d: "Construcción arquitectónica en forma de arco." },
  { w: "Caos", d: "Estado de confusión y desorden." },
  { w: "Destello", d: "Luz intensa y de breve duración." },
  { w: "Enigma", d: "Dicho o cosa que tiene un significado oculto." },
  { w: "Fénix", d: "Ave mitológica que renacía de sus cenizas." },
  { w: "Gélido", d: "Que es sumamente frío." },
  { w: "Hálito", d: "Vapor que arroja el cuerpo por la boca." },
  { w: "Ímpetu", d: "Fuerza o violencia con que alguien o algo se mueven." },
  { w: "Júbilo", d: "Alegría muy intensa que se manifiesta exteriormente." },
  { w: "Kosmos", d: "Palabra griega que significa orden o mundo." },
  { w: "Léxico", d: "Vocabulario de un idioma o región." },
  { w: "Matiz", d: "Grado de diferencia entre dos colores." },
  { w: "Nirvana", d: "Estado de liberación de todo sufrimiento." },
  { w: "Oasis", d: "Sitio con vegetación y agua en un desierto." },
  { w: "Prisma", d: "Cuerpo geométrico con bases iguales y paralelas." },
  { w: "Quimera", d: "Sueño o ilusión que es producto de la imaginación." },
  { w: "Reliquia", d: "Objeto que perteneció a un santo o personaje famoso." },
  { w: "Sosegado", d: "Que está tranquilo y en paz." },
  { w: "Tregua", d: "Suspensión temporal de una lucha o guerra." },
  { w: "Umbral", d: "Parte inferior de la puerta o entrada." },
  { w: "Vértigo", d: "Sensación de falta de equilibrio." },
  { w: "Xenón", d: "Elemento químico de la familia de los gases nobles." },
  { w: "Yermo", d: "Terreno que está despoblado e inculto." },
  { w: "Zénit", d: "Punto más alto en el cielo." },
  { w: "Absorto", d: "Muy concentrado en algo, sin darse cuenta de lo demás." },
  { w: "Baluarte", d: "Construcción defensiva o base de apoyo." },
  { w: "Casuística", d: "Consideración de los diversos casos particulares." },
  { w: "Dilema", d: "Situación en la que hay que elegir entre dos opciones." },
  { w: "Efervescencia", d: "Desprendimiento de burbujas o agitación." },
  { w: "Facetas", d: "Cada una de las caras de un poliedro o aspectos." },
  { w: "Gárgola", d: "Figura tallada para desaguar el agua de lluvia." },
  { w: "Hegemonía", d: "Supremacía que un estado ejerce sobre otros." },
  { w: "Itinerario", d: "Descripción de un camino o ruta." },
  { w: "Jerga", d: "Lenguaje formal de ciertos grupos." },
  { w: "Kilo", d: "Unidad de masa mil veces mayor que el gramo." },
  { w: "Lidiar", d: "Luchar o enfrentarse con algo o alguien." },
  { w: "Mística", d: "Parte de la teología que trata de la unión con Dios." },
  { w: "Nefario", d: "Sumamente malvado o indigno." },
  { w: "Opulencia", d: "Gran riqueza o abundancia." },
  { w: "Pernicioso", d: "Que causa mucho daño o perjuicio." },
  { w: "Quebranto", d: "Gran daño, dolor físico o moral." },
  { w: "Radical", d: "Que afecta a la raíz o esencia de algo." },
  { w: "Sagacidad", d: "Agudeza y prontitud de mente." },
  { w: "Tenacidad", d: "Fuerza que impulsa a continuar con algo." },
  { w: "Utopía", d: "Proyecto o deseo ideal que es irrealizable." },
  { w: "Vasto", d: "Muy extendido o muy grande." },
  { w: "Watio", d: "Unidad de potencia eléctrica." },
  { w: "Yacer", d: "Estar echado o tendido en el suelo." },
  { w: "Zozobra", d: "Estado de inquietud o congoja." },
  { w: "Acantilado", d: "Costa alta y con gran pendiente." },
  { w: "Bizarro", d: "Valiente y decidido (en el sentido antiguo)." },
  { w: "Cúspide", d: "Punto más alto de una montaña o de algo." },
  { w: "Dádiva", d: "Regalo o donación desinteresada." },
  { w: "Elusión", d: "Acción de evitar una dificultad o compromiso." },
  { w: "Flagelo", d: "Calamidad que afecta a un pueblo o grupo." },
  { w: "Genuino", d: "Que conserva sus características propias." },
  { w: "Hípico", d: "Relacionado con la hípica o caballos." },
  { w: "Inane", d: "Vano, fútil o inútil." },
  { w: "Justar", d: "Combatir a caballo con lanza." },
  { w: "Kaiser", d: "Título de emperador en Alemania." },
  { w: "Lóbrego", d: "Oscuro, tenebroso o triste." },
  { w: "Mesura", d: "Moderación y equilibrio en las acciones." },
  { w: "Nómada", d: "Que va de un lugar a otro sin residencia fija." },
  { w: "Oquedad", d: "Espacio hueco en el interior de algo sólido." },
  { w: "Paria", d: "Persona sin derechos o excluida de un grupo." },
  { w: "Quid", d: "Punto esencial de una cuestión." },
  { w: "Rapaz", d: "Ave que se alimenta de otros animales." },
  { w: "Senectud", d: "Edad avanzada o vejez." },
  { w: "Taciturno", d: "Silencioso, callado y algo triste." },
  { w: "Ufano", d: "Orgulloso, satisfecho de sí mismo." },
  { w: "Venidero", d: "Que está por venir o suceder." },
  { w: "Wincha", d: "Instrumento para medir longitudes." },
  { w: "Yugular", d: "Vena gruesa que baja del cuello." },
  { w: "Zafarrancho", d: "Preparativos para una acción o combate." }
];

export const lexicalCuriosities = [
  "La palabra 'reconocer' se lee igual de izquierda a derecha y de derecha a izquierda.",
  "La palabra 'oía' tiene tres sílabas en solo tres letras.",
  "El término 'esternocleidomastoideo' es uno de los más largos en español.",
  "La palabra 'ojalá' viene del árabe 'law šá lláh' (si Dios quiere).",
  "El español es el segundo idioma más hablado del mundo por hablantes nativos.",
  "La letra 'ñ' no es exclusiva del español, existe en el gallego y otras lenguas.",
  "La palabra 'centrifugados' tiene todas las vocales una sola vez.",
  "El término 'murciélago' tiene las cinco vocales.",
  "La palabra 'pedigüeñería' es la única que tiene los cinco signos ortográficos: punto sobre la i, la diéresis sobre la u, la tilde, la virgulilla sobre la ñ y el punto final.",
  "El español tiene aproximadamente 100.000 palabras en el diccionario de la RAE.",
  "La palabra 'euforia' contiene las cinco vocales.",
  "La palabra 'aristocráticos' es un anagrama de 'característicos'.",
  "El prefijo 'super-' debe escribirse unido a la palabra a la que precede.",
  "La palabra 'vía' es de las más cortas con tres fonemas.",
  "La palabra 'corrupto' tiene dos participios: corrompido y corrupto.",
  "La palabra 'setiembre' es aceptada por la RAE, aunque se prefiere 'septiembre'.",
  "El punto sobre la 'i' y la 'j' se llama 'tilde' o 'vírgula'.",
  "La palabra 'yoga' fue introducida al diccionario de la RAE en 2001.",
  "La palabra 'tú' y 'tu' se diferencian por el acento diacrítico.",
  "La palabra 'solo' ya no requiere tilde según las nuevas normas de la RAE.",
  "La palabra 'guion' ya no lleva tilde por ser monosílaba a efectos ortográficos.",
  "La palabra 'amor' es un palíndromo de 'roma'.",
  "La palabra 'sometemos' es un palíndromo.",
  "La palabra 'anilina' es un palíndromo.",
  "La palabra 'arenera' es un palíndromo.",
  "La palabra 'radar' es un palíndromo.",
  "La palabra 'seres' es un palíndromo.",
  "La palabra 'salinas' es un palíndromo.",
  "La palabra 'neurolingüística' es una de las palabras técnicas más complejas.",
  "La palabra 'pseudónimo' puede escribirse también como 'seudónimo'.",
  "La palabra 'abstracto' proviene del latín 'abstractus'.",
  "La palabra 'biblioteca' significa 'caja de libros' en griego.",
  "La palabra 'geografía' significa 'descripción de la tierra'.",
  "La palabra 'filosofía' significa 'amor a la sabiduría'.",
  "La palabra 'democracia' significa 'poder del pueblo'.",
  "La palabra 'telescopio' significa 'ver a lo lejos'.",
  "La palabra 'microscopio' significa 'ver lo pequeño'.",
  "La palabra 'biología' significa 'estudio de la vida'.",
  "La palabra 'psicología' significa 'estudio del alma'.",
  "La palabra 'sociología' significa 'estudio de la sociedad'.",
  "La palabra 'antropología' significa 'estudio del hombre'.",
  "La palabra 'paleontología' significa 'estudio de lo antiguo seres'.",
  "La palabra 'astronomía' significa 'leyes de los astros'.",
  "La palabra 'economía' significa 'administración de la casa'.",
  "La palabra 'política' significa 'asuntos de la polis'.",
  "La palabra 'étimo' es la palabra que da origen a otra.",
  "La palabra 'neologismo' es una palabra nueva en una lengua.",
  "La palabra 'arcaísmo' es una palabra que ha caído en desuso.",
  "La palabra 'eufemismo' es una palabra suave que sustituye a una dura.",
  "La palabra 'cacofonía' es un sonido desagradable al oído.",
  "La palabra 'aliteración' es la repetición de sonidos en un verso.",
  "La palabra 'metáfora' significa 'traslación' de significado.",
  "La palabra 'hipérbole' es una exageración.",
  "La palabra 'ironía' es decir lo contrario de lo que se piensa.",
  "La palabra 'sarcasmo' es una ironía mordaz y cruel.",
  "La palabra 'paradoja' es una contradicción aparente.",
  "La palabra 'oxímoron' es la unión de dos términos opuestos.",
  "La palabra 'epíteto' es un adjetivo que resalta una cualidad inherente.",
  "La palabra 'pleonasmo' es la repetición innecesaria de términos.",
  "La palabra 'solecismo' es un error en la sintaxis.",
  "La palabra 'barbarismo' es un error en la escritura o pronunciación.",
  "La palabra 'dequeísmo' es el uso incorrecto de 'de que'.",
  "La palabra 'queísmo' es la omisión de la preposición 'de'.",
  "La palabra 'laísmo' es el uso incorrecto de 'la' como objeto indirecto.",
  "La palabra 'leísmo' es el uso incorrecto de 'le' como objeto directo.",
  "La palabra 'loísmo' es el uso de 'lo' por 'le'.",
  "La palabra 'polisemia' es cuando una palabra tiene muchos significados.",
  "La palabra 'homonimia' es cuando dos palabras se escriben igual.",
  "La palabra 'sinonimia' es cuando dos palabras significan lo mismo.",
  "La palabra 'antonimia' es cuando dos palabras significan lo opuesto.",
  "La palabra 'paronimia' es cuando dos palabras suenan parecido.",
  "La palabra 'onomatopeya' imita sonidos de la naturaleza.",
  "La palabra 'etimología' estudia el origen de las palabras.",
  "La palabra 'semántica' estudia el significado de las palabras.",
  "La palabra 'sintaxis' estudia el orden de las palabras.",
  "La palabra 'morfología' estudia la forma de las palabras.",
  "La palabra 'ortografía' significa 'escritura correcta'.",
  "La palabra 'fonética' estudia los sonidos de las palabras.",
  "La palabra 'léxico' es el conjunto de palabras de una lengua.",
  "La palabra 'idioma' significa 'particular' en griego.",
  "La palabra 'dialecto' es una variante regional de una lengua.",
  "La palabra 'jerga' es un lenguaje específico de un grupo.",
  "La palabra 'argot' es similar a la jerga.",
  "La palabra 'caló' es el lenguaje de los gitanos en España.",
  "La palabra 'spanglish' es la mezcla de español e inglés.",
  "La palabra 'creole' es una lengua mezclada.",
  "La palabra 'esperanto' es una lengua artificial internacional.",
  "La palabra 'latín' es la lengua madre del español.",
  "La palabra 'griego' ha aportado muchos términos técnicos.",
  "La palabra 'árabe' ha aportado miles de palabras al español."
];
